### ISSUE TITLE
How can i Set permission for a Player only can merge, 2, 4, 6 Plots?

### ISSUE THREAD

**Issue by MonoAdrian23** [KCodeYT/PlotPlugin#10]
Title say all

**Comment by KCodeYT** [comment]
This feature is implemented in the [latest snapshot of 1.1.0](https://github.com/KCodeYT/PlotPlugin/releases/tag/1.1.0-SNAPSHOT).

**Comment by KCodeYT** [comment]
This feature has been added to the [latest release of 1.1.0](https://github.com/KCodeYT/PlotPlugin/releases/tag/1.1.0).
You need to give the permission: plot.merge.limit.\<any number> to the player and the player wont be able to merge more than the given number of plots.
