### ISSUE TITLE
Plot Borders can be Stolen with Sticky Pistons.

### ISSUE THREAD

**Issue by MonoAdrian23** [KCodeYT/PlotPlugin#8]

**Comment by MonoAdrian23** [comment]
Change youre border to beacon or another Block

Place a Sticky Piston powered with Redstone

Now you can steal the Border Block and its Not longer portectected.

**Comment by KCodeYT** [comment]
I cant reproduce this error. Are you sure you are using the latest version of this plugin?

**Comment by KCodeYT** [comment]
I close this issue. If this error still appears, please create a new issue.
