### ISSUE TITLE
Feature Request (/p wall /p wand)

### ISSUE THREAD

**Issue by MonoAdrian23** [KCodeYT/PlotPlugin#9]
Please add an Option for changing Plot Walls

**Comment by KCodeYT** [comment]
Hey I added this feature, can you test it? Its in the prerelease of 1.1.0 (https://github.com/KCodeYT/PlotPlugin/releases/tag/1.1.0-SNAPSHOT)

**Comment by KCodeYT** [comment]
This feature has been added to the [latest release of 1.1.0](https://github.com/KCodeYT/PlotPlugin/releases/tag/1.1.0)
